### ISSUE TITLE
Blog project is not loaded correctly into Solution.

### ISSUE THREAD

**Issue by lgoychev** [PeUzunov/QA-Automation-Team-Project#5]
When starting the solution the prompt message displayed that “One or more projects in the solution were not loaded correctly. Please see the Output Window for details.”

And The Blog project in VS is marked as (**unavailable**) 

See in attachment: 
![pic_1](https://cloud.githubusercontent.com/assets/13354359/25317580/f4f3402e-2883-11e7-8a84-07bf1c0c05c9.png)
![pic_2](https://cloud.githubusercontent.com/assets/13354359/25317582/f887b5ee-2883-11e7-9f55-625103b9b443.png)

**Comment by lgoychev** [comment]
Fixed, please test on your side.

**Comment by Iliev88** [comment]
Fixed.
